default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci

development:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  database: rails_tutorial
  username: app
  password: app

test:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  database: rails_tutorial_test
  username: app
  password: app

production:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
